### ISSUE TITLE
ImportError for sphinx.locale.l_ in Sphinx 3.0.0

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-contrib/domaintools#8]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinxcontrib/makedomain.py", line 20, in <module>
    from sphinxcontrib.domaintools import custom_domain
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinxcontrib/domaintools/__init__.py", line 29, in <module>
    from sphinx.locale import l_, _
ImportError: cannot import name 'l_' from 'sphinx.locale' (/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/locale/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/registry.py", line 405, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.makedomain (exception: cannot import name 'l_' from 'sphinx.locale' (/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/locale/__init__.py))

Extension error:
Could not import extension sphinxcontrib.makedomain (exception: cannot import name 'l_' from 'sphinx.locale' (/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1564/lib/python3.7/site-packages/sphinx/locale/__init__.py))
```

@tk0miya, can you advise what happened to `sphinx.locale.l_`, and I'll make a patch?

**Comment by eric-wieser** [comment]
Ah, solved:

https://github.com/sphinx-doc/sphinx/blob/v2.4.0/sphinx/locale/__init__.py#L269-L272
